### ISSUE TITLE
Corrupts savegames.

### ISSUE THREAD

**Issue by rogerw99** [Nicolas-Constanty/WillowTreeBLDEnhanced#1]
Willowtree 2.3.1 crashes & corrupts the save game whether an edit has been made or not creating a 0 byte file. The result after the error popup is always a 0-byte file. 

[WillowTree#.log](https://github.com/Nicolas-Constanty/WillowTreeBLDEnhanced/files/3051630/WillowTree.log)

[Save0002.zip](https://github.com/Nicolas-Constanty/WillowTreeBLDEnhanced/files/3051633/Save0002.zip)

Edit: Tried ver 2.2.2 & found that I could edit and save changes in save game without any apparent problems. Added items seem to looks & functions correctly. Less functionality & harder to use in comparison to 2.3.1. Many unknown items & no Bank.
Edit 2: 2.2.2 does corrupt save games. After too much editing seems to cause load issues.

**Comment by Nicolas-Constanty** [comment]
That should be fix with the last version
