### ISSUE TITLE
2.3.2 crashes while loading a savegame

### ISSUE THREAD

**Issue by fluxxxus** [Nicolas-Constanty/WillowTreeBLDEnhanced#3]
System.IO.InvalidDataException: String was not properly terminated with a null character.
   bei WillowTree.WillowSaveGame.ReadString(BinaryReader reader, ByteOrder endian)
   bei WillowTree.WillowSaveGame.ReadWeaponStrings(BinaryReader reader, ByteOrder bo)
   bei WillowTree.WillowSaveGame.ReadObject[T](BinaryReader reader, RawDataInfo& rd, Int32 paddingSize, Boolean isDLC)
   bei WillowTree.WillowSaveGame.ReadObjects[T](BinaryReader reader, List`1& Objects, Int32 groupSize, Int32 paddingSize, Boolean isDLC)
   bei WillowTree.WillowSaveGame.ReadWSG(Stream fileStream)
   bei WillowTree.WillowSaveGame.LoadWSG(String inputFile)
   bei WillowTree.WillowTreeMain.Open_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei WillowTree.Program.Main()

**Comment by Nicolas-Constanty** [comment]
Hi fluxxxus, can i have the file that cause this error please?

**Comment by fluxxxus** [comment]
Hi Nicolas,

here is the file. Thanks for your great work!

Greetings from Germany,
Jo

Am Mo., 8. Apr. 2019 um 21:38 Uhr schrieb Nicolas-Constanty <
notifications@github.com>:

**Comment by sparkytwl** [comment]
i am having the same issue, with the same error
[blgoty save.zip](https://github.com/Nicolas-Constanty/WillowTreeBLDEnhanced/files/3056546/blgoty.save.zip)

**Comment by fluxxxus** [comment]
[Save0001.zip](https://github.com/Nicolas-Constanty/WillowTreeBLDEnhanced/files/3056555/Save0001.zip)

**Comment by meachware** [comment]
V2.3.2 crashes on opening all of my save files, however V2.2.2 opens all my low level (<20) files but crashes on my level 28 file.
HTH
Can provide file and thanks for your work on this :)

**Comment by Nicolas-Constanty** [comment]
Thank for your comment, that is fixed with the 2.3.3.
