### ISSUE TITLE
Can't import code from gear calculator via clip board

### ISSUE THREAD

**Issue by raider1001** [Nicolas-Constanty/WillowTreeBLDEnhanced#6]
Hi:

I am trying to import from a code from [Gear calculator ](http://gearcalc.50webs.com) via clipboard but it appear this function is not working (complaining "invalid clipboard data") when compared with 2.2.2 release.

A sample code I am trying to import is the following. I verified that the code made it into the clipboard before trying to import the code into Willowtree.

dlc3_gd_customweapons.Unique_Weapons.CustomWeap_SupportMG_AjaxSpear
gd_manufacturers.Manufacturers.Atlas
gd_weap_support_machinegun.A_Weapon.WeaponType_support_machinegun
gd_weap_combat_rifle.Body.body5
gd_weap_combat_rifle.Grip.grip5
gd_weap_support_machinegun.mag.mag5
dlc3_gd_weap_UniqueParts.SupportMachineGun.barrel5_AjaxSpear
gd_weap_support_machinegun.Sight.sight1
gd_weap_combat_rifle.Stock.stock5
None
gd_weap_combat_rifle.acc.acc3_Shock
dlc3_gd_weap_UniqueParts.SupportMachineGun.AjaxSpear_Material
gd_weap_names_shared.Prefix.PrefixU_blank
dlc3_gd_weap_UniqueParts.Title.TitleU_SupportMG_AjaxsSpear
1
5
0
63

**Comment by Nicolas-Constanty** [comment]
Thank for the report raider,
That should be fixed now with the 2.3.4 #7

**Comment by raider1001** [comment]
It worked for me now, thanks.
