### ISSUE TITLE
Can't import anything on 2.3.3

### ISSUE THREAD

**Issue by khazad11** [Nicolas-Constanty/WillowTreeBLDEnhanced#7]
When i try to import from the clipboard it says "invalid clipboard data, weapon not inserted" but it works with 2.3.2, but 2.3.2 corrupts the save, when i opened the game it was too laggy and when i selected my character it crashed on the loading screen.

I don't know if it was because i used a few old modded weapons that i found on http://blmodding.wikidot.com/hall-of-fame-dlc3 and these weapons doesn't exist on the remaster

**Comment by Nicolas-Constanty** [comment]
You can retry with the 2.3.4, it should work now. I tried with the first weapon of your link and a random shield. 
![ImportBDL](https://user-images.githubusercontent.com/9875531/56319028-e1873500-6160-11e9-9c78-624158384309.jpg)
